spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: {clientID}
            client-secret: {secretID}
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-959730.okta.com/oauth2/default
  jpa:
    hibernate:
      ddl-auto: update
  hibernate:
    hbm2ddl:
      auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test